version: "3.8"
services:
  backend:
    build:
      context: ./backend
    container_name: tray_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
    networks:
      - tray_network
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: tray-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    networks:
      - tray_network

  db:
    image: mysql:8.0
    container_name: tray_db
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
    - "13306:3306"
    volumes:
      - tray_db_data:/var/lib/mysql
    networks:
      - tray_network

networks:
  tray_network:
    driver: bridge

volumes:
  tray_db_data:
    driver: local
