version: "3.8"
services:
  backend:
    build:
      context: ./backend
    container_name: tray-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
    networks:
      - tray-network
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: tray-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    networks:
      - tray-network

  db:
    image: mysql:8.0
    container_name: tray-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_database
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    volumes:
      - tray-db-data:/var/lib/mysql
    networks:
      - tray-network

networks:
  tray-network:
    driver: bridge

volumes:
  tray-db-data:
    driver: local
